

server:
  port: ${MS_LOGIN_SERVER_PORT:8080}
  shutdown: graceful

spring:
  security:
    
    oauth2:
      client:
        registration:
          google:
            #redirect-uri: http://localhost:3000/login/oauth2/code/google
            clientId: ${google.client.id}
            clientSecret: ${google.client.secret}
            scope:
              - email
              - profile
              
  application:

    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      - swaggerEN
      
  zipkin:
    enabled: false
  sleuth:
    baggage:
      remote-fields: X-Client-Ip
      correlation-fields: X-Client-Ip

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it.pagopa.sociallogin: ${MS_LOGIN_LOG_LEVEL:DEBUG}
  pattern:
    additional-info: ",%X{X-Client-Ip:-}]"



